WITH CTE_MERGE_SOURCE AS (
SELECT CURRENT_DATE-1 AS DATA_PROCESSO,
       NOW() AS DATA_ATUALIZACAO
)
MERGE INTO TB_LOG_TEMPERATURA AS A
USING CTE_MERGE_SOURCE AS B
ON A.DATA_PROCESSO = B.DATA_PROCESSO 
WHEN MATCHED THEN
    UPDATE SET DATA_ATUALIZACAO = B.DATA_ATUALIZACAO,
               CONTEUDO = {{params.CONTEUDO_JSON}}::JSON 
WHEN NOT MATCHED THEN
    INSERT (DATA_PROCESSO,DATA_ATUALIZACAO,CONTEUDO)
      VALUES (B.DATA_PROCESSO,B.DATA_ATUALIZACAO,{{params.CONTEUDO_JSON}}::JSON); 
