CREATE  SEQUENCE IF NOT EXISTS PUBLIC.SQ_LOG_TEMPERATURA START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PUBLIC.TB_LOG_TEMPERATURA (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('SQ_LOG_TEMPERATURA'),
    DATA_PROCESSO DATE DEFAULT CURRENT_DATE,
    DATA_ATUALIZACAO TIMESTAMP,
    CONTEUDO JSON,
    CONSTRAINT UNQ_DATA_PROCESSO UNIQUE (DATA_PROCESSO)
);
